/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.KeyController;
import model.KeyRegistro;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;


public class JPainelAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JPainelAdmin.class.getName());
    private KeyController keyController = new KeyController();
    private JTextField tfNovaKey;
    private JButton btnCriarKey;
    private JTable tableKeys;
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form JPainelAdmin
     */
    public JPainelAdmin() {
        initComponents();

        setTitle("Painel do Administrador");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(500, 350);
        setLocationRelativeTo(null);
        getContentPane().setLayout(new BorderLayout());

        JPanel topo = new JPanel(new FlowLayout());
        tfNovaKey = new JTextField(20);
        btnCriarKey = new JButton("Criar Key");

        topo.add(new JLabel("Nova Key:"));
        topo.add(tfNovaKey);
        topo.add(btnCriarKey);

        getContentPane().add(topo, BorderLayout.NORTH);

        String[] colunas = {"Chave", "Usada"};
        tableModel = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableKeys = new JTable(tableModel);
        getContentPane().add(new JScrollPane(tableKeys), BorderLayout.CENTER);

        carregarKeys();

        btnCriarKey.addActionListener(e -> criarKey());
    }

    private void criarKey() {
        String chave = tfNovaKey.getText().trim();
        if (chave.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite uma chave para criar!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean sucesso = keyController.inserirKey(chave);
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Chave criada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            tfNovaKey.setText("");
            carregarKeys();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao criar chave! Talvez já exista.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void carregarKeys() {
        tableModel.setRowCount(0);
        List<KeyRegistro> listaKeys = keyController.listarKeys();

        for (KeyRegistro key : listaKeys) {
            tableModel.addRow(new Object[]{key.getChave(), key.isUsada() ? "Sim" : "Não"});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JPainelAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
